version: '3'

services:
  savvyers-server-dev:
    build:
      context: ../../
      dockerfile: docker/dev/dockerfile
    container_name: savvyers-server-dev
    ports:
      - 5101:8080
    env_file:
      - ../../env/.env.dev
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    networks:
      - default
      - shared-elastic
    restart: unless-stopped

networks:
  shared-elastic:
    external: true
    name: shared-elastic # 기존 네트워크 참조
