version: '3'

services:
  savvyers-server-blue:
    build:
      context: ../../
      dockerfile: docker/prod/dockerfile
    container_name: savvyers-server-prod
    ports:
      - 5201:8080
    env_file:
      - ../../env/.env.prod
    networks:
      - default
      - shared-elastic
    restart: unless-stopped

networks:
  shared-elastic:
    external: true
    name: shared-elastic
